### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by markperryman** [airs-linked-data/lov#43]
It might be easier if we ask to receive current examples of database schemas organizations are presently using so that we can map via one to one relationships to this model.

It could be beneficial to specifically receive a:
- Visionlink customer schema
- RTM customer schema
- iCarol customer schema
- Harmony customer schema
- 211LinQ customer schema

This will tell us if we are missing anything as well as help us to address the sufficiency of specific fields and whether or not we need to improve the field type for better classification, differentiation and attribution.

Thoughts?

**Comment by eric-jahn** [comment]
The pilot has performed this task.
