### ISSUE TITLE
Site.hasSpatialLocation – I’m not sure what this is referring to

### ISSUE THREAD

**Issue by pollymcdaniel** [airs-linked-data/lov#45]
My confusion I guess is that we do not maintain latitude/longitude for the site…our data sets use text only to describe what the service area is for a particular location. (for example an agency has two locations that services are provided from…site one residents from 2 counties can go to, to seek services, while site two – only residents from one of the two counties can go to, to seek services – SiteService is more specific as to which services and assigning geo information) If you’re talking about latitude/longitude for the location of a particular site (and not it’s service area) then isn’t that covered in the address data fields? Can someone shed some light on this?

**Comment by eric-jahn** [comment]
hasSpatialLocation is removed from v0.0.11.  It could be used to precisely define a service area, but that's a future level of precision I think we don't have yet.
