### ISSUE TITLE
airs:Address:  dct:description

### ISSUE THREAD

**Issue by pollymcdaniel** [airs-linked-data/lov#48]
why is there a place for description here…as well as a place for Directions under airs:Site? Wouldn’t this be the same thing?

It was explained to me that, "It would be for any information describing the Site.  Any facts, or tidbits of trivia about the Site, like the name of the building, or the capacity, or whatever.  It wouldn't be for directions on how to get to the Site."

The building name should be part of the address fields, if it applies. I&r services use the Directions data field to capture what you are stating above other than building name. So, this is duplicative. I suggest it be removed. Which brings up an additional question - what exactly are the fields as associated with vCard - does it have the data fields to capture building name, etc?

**Comment by eric-jahn** [comment]
airs:Site directions are meant as instructions for arriving to that location.  And airs:Address description is any additional information the public might need to know about that location, like metadata that this address is used to have a different street name, or anything about it really.  Some examples for vcard are now in the diagram image at: https://raw.githubusercontent.com/airs-linked-data/lov/v0.0.11/doc/airs_vocabulary.png
