### ISSUE TITLE
airs:SiteService - Program Name?

### ISSUE THREAD

**Issue by pollymcdaniel** [airs-linked-data/lov#49]
I do not see anywhere the ability to share a Program Name if one exists? It would be a title, with the option to include alternate names? 

A program name is a name of a group of services that an agency has given to it…from the AIRS Glossary: A proper name for a service or group of services that is specified by the agency, rather than created by the I&R service. In many cases, there is no specific program name for the service/service group. Examples : Toys for Tots, Tough Love.

**Comment by eric-jahn** [comment]
dct:title added to airs:Service and airs:ServiceGroup with v0.0.11.
